theme: jekyll-theme-cayman
title: Hello 
show_downloads: true
description: My name is Ia Mgvdliashvili and I'm graduating from Computer Science program at ELTE Budapest. In August I will return to Georgia and I'll be looking for a job in Tbilisi or remotely. Right now I just want to find out which companies I could apply at, so I can prepare ... TODO