theme: jekyll-theme-cayman
title: Hello 
show_downloads: false
description: My name is Ia Mgvdliashvili, I work as a C++ developer at Ericsson and I'm graduating from Computer Science program at ELTE Budapest. In August I will return to Georgia and I'll be looking for a job in Tbilisi or remotely. 